### ISSUE TITLE
Import/Export der Strategien per chrome Extension

### ISSUE THREAD

**Issue by weyandch** [ptstratx/ptstratx#2]
Die Info zu der Extension ist irgendwo i mChannel verloren gegangen, könnt ihr den bitte in die Doku aufnehmen?

**Comment by ptstratx** [comment]
Machen wir und vorübergehend legen wir ihn mal hier ab.
https://chrome.google.com/webstore/detail/ptstratx-share-settings/kakgppgfnajffmjblicjelmojfafegof

**Comment by ptstratx** [comment]
Link hier aufgenommen:
https://github.com/ptstratx/ptstratx/wiki/How-to-insert-PTStratX-on-TV
Zusätzlich auch noch am Ende der deutschen Kurzanleitung:
https://github.com/ptstratx/ptstratx/wiki/Kurzanleitung
