### ISSUE TITLE
Feature Request: Indikator der den Rise/Drop des BTC anzeigt

### ISSUE THREAD

**Issue by ACETyr** [ptstratx/ptstratx#3]
Die Drop/Rise Trigger in PT2 sind jetzt konfigurierbar(er) geworden (Periode, Markt), was fehlt ist allerdings ein Indikator mit dem man das charten und entsprechend vernünftig einstellen kann.
Wäre toll, wenn man das in PTStratX realisieren könnte, gern auch als "Anhängsel".
Idealerweise zu parametrieren wie die entsprechenden Settings im PT2.

**Comment by ptstratx** [comment]
Ist auf die Roadmap aufgenommen
