### ISSUE TITLE
?

### ISSUE THREAD

**Issue by keithofaptos** [ptstratx/ptstratx#4]
Pennypacker85 <notifications@github.com>
Now that RSI/Stoch has been added into PT (fantastic!). I feel that one of the best ways I can think of to not only improve trades in general, but to protect against fast crashes (like the one just the other day) is to allow us to use the same indicators (in particular RSI/Stoch) across multiple timeframes). Many of the best trading strategies right now are using 5-15 minute candle period low RSI levels to buy. This is great, until you get the 5m RSI showing a low reading while the 1 hour is overbought. The market then continues to drop sharply after you bought based on the 5m and leaves you relying heavily on DCA to pull you out of what are now some quite heavy bags.

To avoid this most Day traders look for confluence across multiple timeframes when they are buying based on an indicator. Rarely does someone buy based on the 5m RSI alone. They might for example buy when the 5m is under 30, the 15 min is also very low, and the 1 hour is at least in the bottom half of its range.

If you were able to allow us to run say, RSI 1, RSI 2 and RSI 3 (even just two would be good but the more the better i guess), with each reading different candle periods, this could go a long way towards making smarter buys and protecting us from sudden crashes (especially because if you are buying on the 5m atm, it is often oversold long before a SOM % change trigger kicks in, leaving you making buys before the protection kicks in).

Just to add (this would be a separate feature I guess, but would go very well in tandem with this), the ultimate here would be being able to connect these RSI periods to % change over time. So just for example:

If there has been more than 2.5% percentage drop within the last hour, PT now requires the 1 hour RSI to be below 30
If there is a minimal % change in the last hour, then PT only requires 1 hour RSI to be below 50
Anyway, just some things I think would really help the bot make consistent buys across a wider variety of market conditions.

**Comment by ptstratx** [comment]
I think that shouldn't be too difficult to realize it.
We will try it in a further release

**Comment by ptstratx** [comment]
An addition:
You can add the new addon for PTStratX several times and thus use several RSI with several different periods.

**Comment by ptstratx** [comment]
We will think about it in the future
