### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by pheonix727** [ptstratx/ptstratx#7]
today ptstratx invite only was working okay, 4 hours again, when i change settings the script doesn't even try to reload , all relevant indicators are not loading
i'm using emaspread, no ema lines

**Comment by ptstratx** [comment]
Hey phoenix727,
please contact us directly to solve this Problem.
these are our english telegram group:
https://t.me/joinchat/E0sioVFomfOEJbRUK6gA_A
We need more details.

**Comment by ptstratx** [comment]
closed due to missing answer
